In [105]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN','londON_StockhOlm','Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )','12. Air France','"Swiss Air"']})
print(df.dtypes)

#start Q-1

flight_no=df['FlightNumber'][0]
for indx in df.index:
    df['FlightNumber'][indx]=flight_no
    flight_no+=10    

df=df.astype({'FlightNumber': 'int32'})
print('\nAfter conversion\n\n',df.dtypes)
df
#End Q-1

#---------------------------------------------------------------

#Start Q-2
dfTemp=pd.DataFrame(df['From_To'].str.split('_',expand=True))
dfTemp.columns=['From','To']
dfTemp
#End Q-2
#---------------------------------------------------------------
#Start Q-3
dfTemp['From']=dfTemp['From'].str.capitalize()
dfTemp['To']=dfTemp['To'].str.capitalize()
dfTemp
#End Q-3

#---------------------------------------------------------------

#Start Q-4
df.drop('From_To',axis=1,inplace=True)
dfNew=pd.concat([dfTemp,df],axis=1)
dfNew
#End Q-4
#---------------------------------------------------------------

#Start Q-5

dfNew['delay_1']=np.nan
dfNew['delay_2']=np.nan
dfNew['delay_3']=np.nan
ls=dfNew['RecentDelays'].tolist() 


for indx in dfNew.index:
    if(len(ls[indx])==3):
        dfNew['delay_1'][indx]=int(ls[indx][0])
        dfNew['delay_2'][indx]=ls[indx][1]
        dfNew['delay_3'][indx]=ls[indx][2]        
    elif(len(ls[indx])==2):
        dfNew['delay_1'][indx]=ls[indx][0]
        dfNew['delay_2'][indx]=ls[indx][1]
    elif(len(ls[indx])==1):
        dfNew['delay_1'][indx]=ls[indx][0]
         
    #print(ls[indx])
dfNew.drop('RecentDelays',axis=1,inplace=True)
print(dfNew.dtypes)
dfNew
#End Q-5

From_To          object
FlightNumber    float64
RecentDelays     object
Airline          object
dtype: object

After conversion

 From_To         object
FlightNumber     int32
RecentDelays    object
Airline         object
dtype: object
From             object
To               object
FlightNumber      int32
Airline          object
delay_1         float64
delay_2         float64
delay_3         float64
dtype: object

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:57: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:62: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,From,To,FlightNumber,Airline,delay_1,delay_2,delay_3
0,London,Paris,10045,KLM(!),23.0,47.0,NaN
1,Madrid,Milan,10055,<Air France> (12),NaN,NaN,NaN
2,London,Stockholm,10065,(British Airways. ),24.0,43.0,87.0
3,Budapest,Paris,10075,12. Air France,13.0,NaN,NaN
4,Brussels,London,10085,"""Swiss Air""",67.0,32.0,NaN